### ISSUE TITLE
Option for only participating commentaries to get email notification

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1023]
Hi Stephen,

Is it maybe possible to create an option in the comment plugin to have only the participating people who make a comment to receive an email notification when a comment is made? If I am correct currently all users that have rights to comments receive a notification. So when a comment is made on an image by Person A, the admin receives an email, when the admin responds in the comment field, Person A and the admin get a notification. When Person B then also gives a comment in the comment field about the same picture, all three participants get an email. etc.

**Comment by sbillard** [comment]
It is probably possible. I will look into it. But some clarification:

For your site there really are no "comments on an image" the person comments on the album and the image title that was being shown is inserted into the comment. If the admin comments via the reply button there is really no direct link to the others who might have commented when the same image is showing.

Same issue kind of exists when person B comments. He may be viewing image X when he makes the comment but the comment may on the last posted comment which is not necessarily about image X.  There is no "thread" organization of comments so you do not really know what the person posting the comment had in mind to comment on without analyzing his comment--a task beyond the capabilities of netpPhotoGraphics.

**Comment by Elinth** [comment]
Thanks for looking into this, I understood the workings of the album comments, mistakenly called them image comments...

**Comment by sbillard** [comment]
Ok, I have a version in test. It will send an e-mail to all posters who would not otherwise get an e-mail via the normal admin path. So, for instance, it will not send you as the administrator, an e-mail, nor will it send e-mails to any of  your users who have comment rights to the album.

The plugin does require a change to the base release. I'll make a dev release with the changes.

**Comment by Elinth** [comment]
Hi Stephen, That is awesome! Will the main admin not get a notification at all? For checking purposes it would be nice is the main admin of the site does get an email.

**Comment by sbillard** [comment]
The main admin gets notifications via the normal (existing() notification path. Same for any users who have COMMENT rights. This plugin does not change that. It sends e-mails to any poster who would not otherwise have got a notification.

**Comment by Elinth** [comment]
Getting some errors when first putting a comment in by a user that has no comments rights:
 NOTICE: "Undefined variable: message" in /srv/disk6/279773/www/.../plugins/commentNotice.php on line 91
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/.../zp-core/functions-basic.php:117)" in /srv/disk6/279773/www/.../zp-core/functions-basic.php on line 761
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/.../zp-core/functions-basic.php:117)" in /srv/disk6/279773/www/.../zp-core/zp-extensions/comment_form/functions.php on line 655

**Comment by Elinth** [comment]
This is on the latest DEV release

**Comment by sbillard** [comment]
That would happen if there were no e-mail address in the comment. The code that needs to be changed is at the end of the plugin.
`}
		$on = gettext('Comment posted');
		$result = npgFunctions::mail("[" . $_gallery->getTitle() . "] $on", $message, $receipients);
	}
`

move the first "}" to after the second one.

But if there is no e-mail address in the comment the user will not get a message. Be sure that the e-mail address is a required field.

**Comment by Elinth** [comment]
Hi Stephen,

My testuser did have an email address, it's a required field in my site.

**Comment by sbillard** [comment]
There was a bug in the plugin if the only prior posts were from the same user who just posted. (It does not notify the poster since presumably he knows he just posted. That was not handled correctly.)

[commentNotice.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3516730/commentNotice.zip)

This version adds notification when the admin marks a post "approved"

Requires deve release 2.00.01.07.02

**Comment by Elinth** [comment]
Works like a charm!

**Comment by Elinth** [comment]
Thanks so much! You rock!

**Comment by Elinth** [comment]
Are these changes in 2.00.01.08 already?

**Comment by Elinth** [comment]
There is an error in the image.php page when posting a comment. EXCEPTION (0): "Call to undefined method Image::getParent() in /srv/disk6/279773/www/site/zp-core/functions.php on line 288" in /srv/disk6/279773/www/site/zp-core/classes.php on line 473

**Comment by sbillard** [comment]
Yes, the commentNotice plugin does not work correctly for images (since it was designed for the album page.) It fails trying to get the first level album of the image. The function used for that works only on albums (currently.) I think it should work both for albums and images--makes sense anyway. I will make that fix in a development release shortly.

I also note (when investigating this) that you have some errors in your debug log. `printLatestComments()` must be supplied at least the number of comments you want printed. The other error is because there is no function `printComments()`. Probably you want to use `printLatestComments()`

**Comment by Elinth** [comment]
Thanks for looking into the comments for both images and albums. Indeed makes sense.

Yeah, the errors.. 
I was fiddling around to make a guestbook with comments in Zenpage. What I tried to do is display the comments somewhere else then next to the comment form. This to make it appear more like a guestbook. I guess both are tied up in the same function and I can not print the comments seperately then the form. Ha ha, so another feature (that would be quite simple to create I think). A guestbook..

**Comment by sbillard** [comment]
The 2.00.01.08.01 development release should fix the above error.
