### ISSUE TITLE
Rebranding styling of buttons and search options, no more divs

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1087]
Hi Stephen,

Still so happy with NPG,. Just one problem I recently ran into. Since the recent rebranding of NPG I cannot style the buttons anymore of the search submit button, comments submit button, etc. These items are now styled within a span class instead of divs. I aligned them previously to my theme and this seems not possible anymore as the divs are gone. The same is with the reset buttons that I previously didn't display. Is it possible to put them into divs again? My buttons now are not aligned and the same accounts for the search options extra menu that is misaligned in my menu bar now. As always thanks for your great support!

**Comment by Elinth** [comment]
Just figured out the submit buttons as the divs were changed... However the reset and search extra menu I cannot seem to change.

**Comment by Elinth** [comment]
Maybe it would be a nice option, hide search extra menu and hide reset buttons?

**Comment by sbillard** [comment]
I did change the style names to avoid conflict with theme buttons. It does not matter if the style is attached to a DIV or a SPAN although there are sometimes differences in browser rendering between DIV and SPAN. `searchextrashow` is a element ID. You should have no problem styling it or its contents.

THe search extra menu will not be present if there is only one "field" allowed for the search. (That is you have no choice, so no dropdown to choose.) It will show if you are within search context because you might wish to select a new search versus a search within the previous results.

Not sure what reset button you are concerned about. There is none for search. If the button is one of the netPhotoGraphics reset buttons it has the same styling classes as the other buttons.

**Comment by Elinth** [comment]
Hi Stephen,
I would like to only hide the menu icon from the searchextrashow. The menu itself is no problem, this listens to searchextrashow, but I cannot seem to hide this hamburger menu.
The reset button is the one on the login form. I cannot seem to hide it after many attempts.

**Comment by sbillard** [comment]
I can add a style span to the menu button, but I do not understand your wanting to hide it. Without the button the user cannot select the fields to search nor can he choose between the _within_ and _new_ searches.

It is also not a good idea to hide the login reset button. That lets the user clear the logon form. But if you really want to hide it, the button has a class _resetbutton_ attached to it.

**Comment by Elinth** [comment]
If you can add the style span to the menu button thanks, this way I can align it. I will keep it, you are right in the user possibilities. I am not a bit fan of the reset button, a matter of taste.. 
I tried:
#resetbutton {
display: none;
}

That didn't work.

Also I tried:
button[type=resetbutton] {
 display:none;
}

That didn't work
Could you point me in the right direction?

**Comment by sbillard** [comment]
.resetbutton {
display: none;
}


-Stephen

**Comment by Elinth** [comment]
Tried that... doesn't work...

**Comment by sbillard** [comment]
`			.resetbutton {
				visibility: hidden;
			}
`

I really do not know why the display:none; did not work!

**Comment by Elinth** [comment]
I found it, ZPArdoise uses two stylesheets. Most of it is in screen.css. Your last code worked in the light.css stylesheet. Thanks for your support Stephen!

**Comment by sbillard** [comment]
The dev release has a style span for the searchextra button.

**Comment by Elinth** [comment]
Thanks!!

**Comment by Elinth** [comment]
Hi Stephen,
I am getting loads of errors while running setup on the latest DEV 05..

**Comment by Elinth** [comment]
Running setup again fixed it
