### ISSUE TITLE
Legacy converter problem

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1112]
I'm sorry - you're going to get fed up with me!
I tried using the "Legacy converter" on the theme I've been developing - mainly because my PHP expertise is limited to copy/paste and amateur hacking so I have a certain anxiety about things.

The result was all the files in the theme have in them
> /* LegacyConverter v2.00.04.00 was here */

however it also left a PHP closing tag "?>" at the end of every file - this was easy enough to deal with, but what is far more difficult is a closing tag _which I cannot find anywhere_ and which wrecks my layout because it makes a stripe across the top where it's printed _and_ more importantly it does something I don't understand at all: it appears in the inspector just after the opening "head" tag and the effect is to push the data that should be in the head to _below_ the "body" tag. So page reads that the head is empty and all the meta data, script loading information, etc. is in the document body.

I have not a clue where to look - I went as far as retyping the _head.php letter by letter to see if that would purge it - and now I notice it pops up in the admin pages as well, so that excludes my theme files from blame at any rate.
And that is why I decided to try a fresh install - giving rise to the previous issue.

**Comment by OldNick** [comment]
An update - my bad - in trying to solve the closing tag problem I'd introduced a second Doctype HTML declaration into the document head and it was bouncing (why? How?) everything southwards...
The closing tag dilemma remains however.

How do you transfer your configuration and content to a new install? I tried using a backup from the old install and broke everything...

**Comment by sbillard** [comment]
The extra `?>` PHP tag should be fixed in the current release. But you may have to re-run the legacy converter to remove extra ones left there by the older converter.

The general rule of thumb for moving an installation is:

1. Insure that you have the same version of nPG for both sites. Best to upgrade the old site first.
2. Take an nPG backup on your old site
3. Copy your album folder to the new site.
4. Copy the backup you made in step 1 to the new site (and note its name.)
5. Install nPG on the new site. It should offer you the option of restoring from the backup. If not do that manually.

**Comment by sbillard** [comment]
Is this ticket related to the hosting service in #1115 that you abandoned?

**Comment by OldNick** [comment]
No, it was on a local install - one of those times I didn't need to click on a button but did. As I'm completely new to Netphotographic, the code should be good - but I clicked anyway.
It didn't find any issues (needless to say)
