### ISSUE TITLE
User's password is logged in plaintext on unsuccessful login

### ISSUE THREAD

**Issue by mazdader** [netPhotoGraphics/netPhotoGraphics#1118]
Right now in case of unsuccessful login, the password is logged to `security.log` in plaintext and is available to netPhotoGraphics site administrators. Failed login attempts may occur not only if password is incorrect but, for example, if LDAP server is unavailable. My fix for the issue in `security-logger.php`:
```diff
293c293
> 		security_logger::logger((int) ($success && true), $user, $name, 'Back-end', $auth, 'password_masked');
---
< 		security_logger::logger((int) ($success && true), $user, $name, 'Back-end', $auth, $pass);
342c342
> 		security_logger::logger((int) ($success && true), $user, $name, 'Front-end', $athority, 'password_masked');
---
< 		security_logger::logger((int) ($success && true), $user, $name, 'Front-end', $athority, $pass);
```

**Comment by sbillard** [comment]
It is deliberate that the password is in clear text. This is an important piece of information when analyzing hacking threats to the site. The Administrator is a trusted user. There really is no security issue for him seeing the password in the normal nPG handling since he has the ability to change it or do any other damage to the user he chooses.

The log can be encrypted so exposure of the password is limited to administrative users.

I will have to think about this for a while. I am not sure there is any way to tell if a user "intended" to login via LDAP and ended up with the normal nPG login.

**Comment by mazdader** [comment]
In my organization it's a security incident if any administrator even in theory may become aware of someone's password. These incidents must be reported and the user is enforced to change the password. On the other hand, I totally agree that it's handy in case of troubleshooting and investigations. So since it's a simple fix, I'll document that on our side and the issue can be closed. Thank you.

**Comment by sbillard** [comment]
You have a couple of options on how to deal with this generally. One would be to turn off logging logon attempts in the security logger plugin options. un-check admin_login_attempt and guest_login_attempt.

The other is to create a plugin that filters these actions and masks the password. That filter needs to be at a higher priority than the security logger filter.

**Comment by Elinth** [comment]
Fully agree with Mazdader. I noticed and mentioned this before as well. It makes me really uncomfortable when I see a user's password, as they might use it for other private purposes as well, it is a definate security breach... Even if the user makes a typo (In my case most of the times it is due to case sensitive letters so you can see their actual password) The password is personal and private, and should remain that way, even for admins. Admins give temporary passwords and inform the user it is temporary and they should change it. Probably a GDPR problem too.

**Comment by sbillard** [comment]
As mentioned above, you can prevent the logging or mask the password if that is your concern. GDPR is about disclosing user information, not collecting it (so long as you tell the user what you collect.)
