### ISSUE TITLE
ERROR when quest try to see large images

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1142]
NPG 2.00.04.11, Bootstrap theme

Guest user cant see large images, registered user can... (after click on thumb)

![obrazek](https://user-images.githubusercontent.com/7648991/77585565-f75eb780-6ee4-11ea-84c5-f0168fe63547.png)

but showing images after click on title works.

Have I any bad setting for unregistered quests (gallery is public)?

**Comment by sbillard** [comment]
Please check your image options for the "Full image protection" option. I have tried this on my test site with the Bootstrap theme and all seems to work.  Perhaps you can provide a link to the failing image? maybe that will tell me something.

Clicking on the title would take the user to the image page which loads the image, so maybe there is a problem with caching.

**Comment by Mates-K1** [comment]
My setting is:
![obrazek](https://user-images.githubusercontent.com/7648991/77617962-b3e06980-6f35-11ea-9a5b-6244be2c82fb.png)

So... when I change it only to Unprotected, it works.

**Comment by sbillard** [comment]
Ok, I guess that the theme really does not expect that the image would be set to downloaded rather than displayed. It should also work being set to "protected view" but unless there is some need for that level of protection you should leave it at "unprotected" because that is less overhead on the site.
