### ISSUE TITLE
Create a panorama plugin

### ISSUE THREAD

**Issue by sbillard** [netPhotoGraphics/netPhotoGraphics#1157]
Here is the first pass at the plugin. There is at least one issue I have to figure out. The panorama does not work unless the image is already in the cache. So, first time you display it there is no image shown. Refresh the page and it will be there. I have to figure out how to deal with this.
[panorama.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/4548063/panorama.zip)

**Comment by nerdykit** [comment]
> On Apr 28, 2020, at 12:28 PM, Stephen <notifications@github.com> wrote:
> 
> Here is the first pass at the plugin. There is at least one issue I have to figure out. The panorama does not work unless the image is already in the cache. So, first time you display it there is no image shown. Refresh the page and it will be there. I have to figure out how to deal with this.
> panorama.zip <https://github.com/netPhotoGraphics/netPhotoGraphics/files/4548063/panorama.zip>
Thanks.  Will try it out now.

Kit

**Comment by nerdykit** [comment]
Hmmm.  Well, I put the two files into my plugins folder, and went to configure for the plugin, enabled it and had a configuration issue (but read on) Configuration issue was it didn't like 0.5 as the value to position the start point, would only accept 0 and probably 1 although I didn't try that so just went with zero.

Specified 2000 px as the "trigger" width and 700 px as the height and then tried to view a panoramic file that I had already put into a test album and then viewed it.  Looked exactly as it would have without the plugin. Just a long narrow image (same image that I sent to you).  So definitely not working.  Tried screen refresh, no change.  Then decided to use the admin menu on the right to return to plugin options and at that point screen went blank!  Can't reconnect to the site at all.  Any attempt to use the gallery is just blank.  Can't get back into it at all.

If I just go to the appropriate directory as if I were trying to visit the gallery I get an empty index of the contents (incomplete I guess because I've probably got my apache2 set to NOINDEX).

So essentially it's just clobbered my installation and I can't even get into it to try to figure out what's wrong.  Have used ftp to remove the panorama folder and php file but no change.

Kit

**Comment by nerdykit** [comment]
Now I'm REALLY confused.  Just went in again and my site functions again.  Will try the plugin all over again.

Kit

**Comment by nerdykit** [comment]
Essentially the same result.  I can view the image once (although I get no paver function) just the image scrunched into the available space so long and narrow.  Then all I can get is blank screens.

Dunno why going away and having lunch and coming back and trying again made any difference but after a long time, it seemed the site started to function again.  Not this time....yet.

Kit

**Comment by nerdykit** [comment]
The only thing I can think of is that php gets sent off on some task that it takes about an hour to complete.  Will try looking at php logs to see if I can learn anything.

Kit

**Comment by sbillard** [comment]
I am using 200 px for the threshold trigger and 400px for the height. Your image works for me. I do see that the start position option does not allow decimal points. Have to fix that!

You did put the plugin in the npgCore/Extensions folder?

i've got a new version going now that fixes the initial view issue. It will require some changes to the core, so I will make a development build of it. First, though, I'll fix the  position option.

**Comment by nerdykit** [comment]
> On Apr 28, 2020, at 2:57 PM, Stephen <notifications@github.com> wrote:
> 
> I am using 200 px for the threshold trigger and 400px for the height. Your image works for me. I do see that the start position option does not allow decimal points. Have to fix that!
> 
> You did put the plugin in the npgCore/Extensions folder?
> 
> i've got a new version going now that fixes the initial view issue. It will require some changes to the core, so I will make a development build of it. First, though, I'll fix the position option.
> 
> 

I used a much wider trigger width of 3000.  Right now my nPG has gone south.  I’m assuming that given enough time it will recover but I suspect that somehow it’s been sent into a spin and that it eventually completes whatever task it’s gone off to do.  I had put the new plugin into the plugins folder for “personal” plugins (the one just at root level of the nPG install).  Next test (should I get one), I’ll put it into extensions.

Am going to take a look at php logs to see I can learn anything.

Kit

**Comment by sbillard** [comment]
I don't think that any of the paver js would have loaded if the plugin was in the "plugins" folder, so that could be the issue. I have an update in the development release https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.05.04.01.zip that now includes the panorama plugin.

remove the old plugin from the personal plugins folder or it will try to conflict.

I ran into one styling issue and removed a box-sizing element from the paver CSS. Don't know how that might impact paver. I did not see any issues in my testing, but be aware.

The start position is now a slider. You should set it before trying anything, the old option value may cause problems.

The paver documentation suggests 200 for the trigger. 3000 sounds pretty large.

**Comment by nerdykit** [comment]
> On Apr 28, 2020, at 4:27 PM, Stephen <notifications@github.com> wrote:
> 
> I don't think that any of the paver js would have loaded if the plugin was in the "plugins" folder, so that could be the issue. I have an update in the development release https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.05.04.01.zip <https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.05.04.01.zip> that now includes the panorama plugin.
> 
> remove the old plugin from the personal plugins folder or it will try to conflict.
> 
> I ran into one styling issue and removed a box-sizing element from the paver CSS. Don't know how that might impact paver. I did not see any issues in my testing, but be aware.
> 
> The start position is now a slider. You should set it before trying anything, the old option value may cause problems.
> 
> The paver documentation suggests 200 for the trigger. 3000 sounds pretty large.
> 

Thanks.  I don’t think I understand the width setting then.  I thought that you’d want a pixel width that was clearly very much wider than the height so that the file being displayed via paver was obviously a panorama.  Will go back to look at the paver documentation.

Still haven’t got a working instance of my server back.  Have just rebooted it to see if that helps (I’d already restarted apache but that brought no change).  If I go to check the source of my blank pages, it’s just nothing.

So I figure that php has been sent off on an impossible or at least very long task.  Nope.  My instance of nPG is not responding.  Have cleared browser cache and restarted the server.  Apache is serving files, just not the ones from nPG.  Weird.  php is functional, it will respond to phpinfo request.

Will send you a link to the actual web site so you can see what it’s doing.  Will send it via the stephen billiard email so that I don’t end up posting anything private here.

Kit

**Comment by nerdykit** [comment]
I'm going to set up a clean install of nPG as a test setup.  Meanwhile I've no idea how to restore my existing nPG instance.  It was running the latest release version but has been a working nPG instance for well over 5 years.

**Comment by nerdykit** [comment]
Just downloaded a fresh 2.00.05.03 and did a manual re-install and nada.  Wow, it's really broken.
Setup only reported a red X on access-threshold.  No idea what's going on.

**Comment by nerdykit** [comment]
I think what's going on with my installation when I tested the panorama plugin is that I have something like 15,000 images there and the plugin set out to either cache them all or do something else to the entire collection of images and as a result it just hangs the software for about four hours or while it is completing the task. Then, magically the installation begins to function again. Testing on an installation with only a few images won't reveal this. The hang up may have also been because I had a poorly chosen value in for the width parameter and I installed the plugin into the wrong plugins directory.

**Comment by sbillard** [comment]
Pixel width is how much of the picture to allow to be beyond the 
container befor the image is panned. So it should not be tiny or you 
will get pans that do nothing but it should also not be huge or lots of 
the picture will not be visible and it will not pan.


-Stephen

**Comment by sbillard** [comment]
The build with the plugin is 2.00.05.04.01, so as long as you had removed (or not installed) the first plugin above the plugin will have nothing to do with the response. Your front page is not nPG. Maybe that software is trying to load all the images. When I visited your site I did notice a slow load with first a full sized image that later was scaled down onto the page.

**Comment by sbillard** [comment]
Do you by any chance have either the ipBlocker or accessThreshold plugin enabled? If so disable them. There may be some conflict with what paver does and one of those plugins. I experienced a similar issue to yours on one of my test sites. I am not sure if I had either of those plugins enabled, but I deleted the scripts for both and the site came back immediately. That leads me to believe that one of them kicked in and blocked your access to the site. the symptom would be just what you described. The site would be gone for a while then magically (actually a time out) come back.

On another note, I've made some small changes to the plugin. Latest DEV releases are here: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by nerdykit** [comment]
> On Apr 30, 2020, at 2:53 PM, Stephen <notifications@github.com> wrote:
> 
> Do you by any chance have either the ipBlocker or accessThreshold plugin enabled? If so disable them. There may be some conflict with what paver does and one of those plugins. I experienced a similar issue to yours on one of my test sites. I am not sure if I had either of those plugins enabled, but I deleted the scripts for both and the site came back immediately. That leads me to believe that one of them kicked in and blocked your access to the site. the symptom would be just what you described. The site would be gone for a while then magically (actually a time out) come back.
> 
> On another note, I've made some small changes to the plugin. Latest DEV releases are here: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B <https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B>

I think I  DO have ipBlocker in place and accessThreshold in there.  I recall getting the red X on accessThreshold once during one of many recent installs in an attempt to get things working again.  I’ve set up a test site and after an initial test it worked fine and since then I’ve had problems.  I will try just out and out removing those two plugins and see if that makes any difference.

Kit

**Comment by nerdykit** [comment]
I think that the panorama plugin now works really well.  The trick is making a good decision on the height and then the width overflow so that it only triggers on images that are the ones you want to display that way and of course users who don't have any such images can just leave it disabled so it's a non-issue for them.  Probably the default state for the panorama plugin should be "off" for upgrades or new installations.  As far as I'm concerned, this issue is ready for closure.

**Comment by sbillard** [comment]
I understand the issues with sizing. I haven't figured out an optimal yet. As to the plugin state, it will not automatically enable.

he way the plugin works is that it will do an in-line cache of the image if it is not already cached, then use a link to that cached image. You can check by inspecting the element. It is possible that the in-line cache failed if the image is particularly large. If so the link will be to i.php.

**Comment by nerdykit** [comment]
I just added a couple more images to my test site but I visited the images admin page (to edit the image Titles) for that album **before** my first viewing of them.  Both images did not then require a page refresh before they were visible as panoramas.  Don't know if this helps, just an observation of the behavior of the plugin.

**Comment by sbillard** [comment]
I think that confirms that the other images were too large to process in-line.I suppose the script could force a re-load if that happens. Have to figure out how to do that, though.

**Comment by sbillard** [comment]
Well, looking into it, I think it is not a good idea to try to force the reload. If the image is too big to be cached at all, that would cause the site to go into a loop. I can add a note to the plugin that this situation might occur. If the site owner views the panoramas than they will get cached (except for the really big ones I am concerned about above.)

Your thoughts would be appreciated.

**Comment by nerdykit** [comment]
I think that your instructions in the Note at the end of the panorama information panel are clear.   It seems to me that at one point it was possible to flag a plugin with a "caution" (a red exclamation mark?) so that the action of enabling that plugin forced a warning window to open.  In this case the warning might read something like "Panoramic images can be very large files; there is the possibility that using this feature can cause server problems when used with very large image files-- enable with caution."

**Comment by sbillard** [comment]
Good idea. Yes, there is a "plugin warning"  capability. I will add that note as a warning.

Here is what I think it should say:  "Panoramic images can be very large files; It is the possibility that they may be too large for netPhotoGraphics to render to the cache. You should check that your panoramic images are working. Reduce the size of ones that fail."

By the way, if you do have such large images that they cannot be cached, The won't show with or without the plugin.

**Comment by nerdykit** [comment]
Your wording sounds good.  I'm relieved to see that the result of a panorama "fail" might only be that the image won't display.  I thought that attempting to cache an overlarge image might hang the server which really DOES warrant a warning.
