### ISSUE TITLE
File permisions of duplicated themes

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1210]
nPG 2.00.07.00
When I duplicate theme, files have permision 0600. So pages are "broken".

I think it should be about 0640 or 0644.

**Comment by sbillard** [comment]
Permissions of 0600 should work if the site users are configured correctly. The site should be configured so that the script executions run under the "owner" who does have read/write permissions. Possibly the script execution is running under a different user who is in the "group". In the worst case (for security) the script execution would be running "public".

You can experiment by setting the permissions for the group as well as the owner--0660 or for everyone--0666.  What are the permissions of your config file? Those are the ones that are applied to the copies.

In the meantime, I will change the copy function to propagate the permissions of the original file which will work so long as the site itself works with the defined permissions.

**Comment by Mates-K1** [comment]
0640 works for me.

npg.cfg.php is 0600.

**Comment by sbillard** [comment]
That indicates there is a problem with the website security configuration vs your "file permissions" setting. Does your config file have a line like `$conf['CHMOD'] = 0600;` or any other value? It should probably be `$conf['CHMOD'] = 0640;`. There may be other places where nPG creates files and sets their permissions based on this that may or may not cause problems.

**Comment by Mates-K1** [comment]
Yes.
`$conf['CHMOD'] = 0644;`
