### ISSUE TITLE
Admin --> Assignments - tooltip

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1217]
There is a strange tooltip in Assignments ended with

![t](https://user-images.githubusercontent.com/7648991/93718849-074b1180-fb7f-11ea-9679-015dfde6dd6a.jpg)

![t2](https://user-images.githubusercontent.com/7648991/93718852-0ca85c00-fb7f-11ea-8369-02ebbf7532d5.jpg)

Note: Language is set to english, but tooltip is in czech.

**Comment by sbillard** [comment]
This is due to a mishandling of the group description. The descriptions are translatable strings, but the code was not fetching the specific language, instead it was using the whole database entry. But just to note, the reason that the tips are in Czech is most likely that there is only the czech translation.
