### ISSUE TITLE
Question re: panorama viewed on iPad

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1244]
The behaviour of a panorama image seems to have changed when viewed on an iPad.  Either this is due to a setting that I've accidentally made somewhere for touch screen capable devices or ???

The former behavior was that the scroller could be moved left-right by touching and dragging on the tablet screen.  Now the left-right scroll action is not controlled that way; instead it's controlled by slightly tilting the tablet left side up right side down for instance to slide the panorama scroller to the right and the opposite "tilt" to slide left.  I'm just curious about why it changed or if the scrolling action on a tablet type device is selectable or a specific setting somewhere.

Thanks

**Comment by sbillard** [comment]
The only thing that has changed is the "overlap value", that is how much bigger the image needs to be than the container. That is now zero instead of an option. That change would just make the panning available on some smaller images that (given the option) might not have had it.

The behavior you describe sounds like a device setting, but I do not know.

**Comment by nerdykit** [comment]
Thanks.  I can see that tilt is a boolean that enables/disables this tilt behavior for tablets and I manually edited it to be off in the jquery.min.js file and what happens is that the panorama then can't be "panned" on a tablet (no touch sensitivity) so this behaviour is the standard for tablets or any device with gyro and I'll be happy with it.  Will close this question.
