### ISSUE TITLE
Sitemap-extended - two missing dot (smallest bug ever :D )

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1247]
Sorry, I translate... so I find these small things...

I think if sentence starts with capital, is should ends with dot.

There are two senctences with no dots at the end.

sitemap-extended
- line 172: 

> Also, if your site is really huge think about if you really need this setting as the creation may cause extra workload of your server and result in timeouts

- line 179:

> Must be an absolute URL address of the form: ' . FULLWEBPATH . '/license.html

**Comment by nerdykit** [comment]
I find that ending a sentence involving a URL with a period can cause problems because of the role of dots within the URL.  The first one, line 172 should properly end with the period but I’d break that rule for line 179 and just let it end without one.

**Comment by Mates-K1** [comment]
I agree with potential problem in URL. But in this case, text is in the popup help and URL is not clickable.

**Comment by nerdykit** [comment]
I was an IT teacher in another life and I found that when providing help to users who will be carefully following the directions from the popup help, they can be confused about the trailing period in the URL.  Those of us who know what is involved in a URL know not to have a trailing period after the .html but beginners don’t necessarily know this which is why I made the recommendation for line 179.  Most users who are running nPg are fairly experienced so it probably won’t be a problem either way.
