### ISSUE TITLE
Album map shows wrong location

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1308]
Right location in image...

![obrazek](https://user-images.githubusercontent.com/7648991/111001667-7e21d400-8384-11eb-9a02-488b34b1f1bd.png)

This location is right:
![obrazek](https://user-images.githubusercontent.com/7648991/111001770-aad5eb80-8384-11eb-9de2-2304e340a913.png)

But album map says: 

![obrazek](https://user-images.githubusercontent.com/7648991/111001828-cb05aa80-8384-11eb-9843-561e00eb03e6.png)

**Comment by Mates-K1** [comment]
Žamberk is right position, mark near Uhersko is wrong location.
![obrazek](https://user-images.githubusercontent.com/7648991/111002310-80d0f900-8385-11eb-9bfc-97b31b14d338.png)



My another album: another right position in images, but SAME wrong location.

**Comment by sbillard** [comment]
Have you checked this with the googleMaps plugin? Could you zip up the album and let me have it so I can investigate?

**Comment by Mates-K1** [comment]
Yes, google maps are wrong too.

[brigada_2015_10_28_montovani_nabytku.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/6134770/brigada_2015_10_28_montovani_nabytku.zip)

**Comment by sbillard** [comment]
I suspect that there is a number formatting issue, but I cannot reproduce the issue. Here are the Google and Openstreetmap maps I get for your album. Maybe try setting your locale to en_US and see if the problem is resolved.

<img width="599" alt="2021-03-13 13_02_57-brigada_2015_10_28_montovani_nabytku _ Development _ Home Link" src="https://user-images.githubusercontent.com/2474007/111044303-874e8780-83fc-11eb-9830-f19ebf550034.png">

**Comment by Mates-K1** [comment]
I set it to en_US.UTF8, refresh metadata and it works, so you are right.

**Comment by Mates-K1** [comment]
You use "dot" in GPS, we use decimal point.

![obrazek](https://user-images.githubusercontent.com/7648991/111047711-61050800-844d-11eb-922a-51a156e53c40.png)

![obrazek](https://user-images.githubusercontent.com/7648991/111047870-6a8e7000-844d-11eb-9e45-1a614f3ce72c.png)


Yes, wrong position is exactly  50 N, 16 E... without decimal places.

**Comment by sbillard** [comment]
It is not quite that simple. When a number is passed to a javascript function, the comma is a  parameter separator.

**Comment by sbillard** [comment]
I am unable to reproduce this problem. I have set my site to Czech and still get the correct display, Please try yourself https://testalbum-2.sbillard.org/test_two/brigada_2015_10_28_montovani_nabytku/

I note that there is a possible issue in openstreetmap (although I do not see it) where the coordinates are placed in quotes rather than simply a number. If only openstreetmap had the issue this might be the cause.

How about a link to your album?

**Comment by Mates-K1** [comment]
Your album shows me right coordinates.

I tried your modification of openstreetmap plugin, but it didnt help me.

Please check your e-mail, I sent you link to my album and login.

**Comment by sbillard** [comment]
Ok, I have looked at your site. There is some problem with  the PHP function number_convert. It is used to insure that the number representation for javascript uses the dot as the decimal separator. The output of the function has set the decimal part of the coordinate to zeros.

could you add some debugging code to openstreetmap? Circa line 699 the plugin is outputting the $geodata array. could you please do a `var_dump($geo['lat'],$geo['long']);` so we can see how the input data is formatted. You could also look into the database and see the same information.

**Comment by Mates-K1** [comment]
Hi Stephen, I think you will do next steps much more better and faster then me.  (I got some exception error too...).

Could you please do it yourself?

Please check your e-mail.

**Comment by sbillard** [comment]
Unfortunately, I cannot do it because it is something to do with your server/locale processing. The problem does not exist with your album for me.

But maybe the DEV release will fix it?

**Comment by Mates-K1** [comment]
Yes, DEV release fixed it. :D 

Thanks, Stephen. 👍
