### ISSUE TITLE
Nikon exif exception

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1364]
![Screenshot 2021-11-09 at 07-49-14 https skautskagalerie cz](https://user-images.githubusercontent.com/7648991/140885318-5c6ddc10-316c-4ecf-ae08-cb653cec927e.png)

![obrazek](https://user-images.githubusercontent.com/7648991/140885406-bb5c0281-1c19-489f-969c-df6604f2328b.png)

And here is the first image from the album, which is not shown (there's five albums in total):
[01.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/7502988/01.zip)

**Comment by sbillard** [comment]
change line 328 of makers/nikon.php to `if ($model == 1 && is_numeric($data))` There is probably something wrong with the image or maybe with the nikon exif handling, but since the comment on the code seems to say that it does not know what this feature is, just avoiding the error is probably ok. Anyway, it is strange that the code is dividing something by 100 when it does not know what the something is.

**Comment by Mates-K1** [comment]
Thanks, it works. As usual 🥇
