### ISSUE TITLE
EXCEPTION (8192): "Implicit conversion from float 7.162 to int loses precision"

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1478]
In one of my album I have many exceptions:
![obrazek](https://user-images.githubusercontent.com/7648991/214654376-5d6354ac-e0a9-4620-ab27-d2e02347af2e.png)

I am attaching one of the photos.

These are photos that have "weird" exif information. Some time ago I think there was some bug in nPG that overwrote the description of the photos when restoring the metadata. These are some of the photos that did that.
[04_bad.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/10503281/04_bad.zip)

**Comment by sbillard** [comment]
I can fix the error message, but the data is indeed somehow corrupt. It is a floating point number instead of a string as the code expects. The fix insures that the parameter is a string, but no way to know if the float is the correct string.

**Comment by sbillard** [comment]
I did some more investigation. Turns out this issue was caused by two factors. First there was a bug in the Olympus exif handler that was calling intel3Moto() on a floating point value that was created by the unRational() number converter. The first function reverses the byte order of data from little ending to big ending since all the exif code expect the latter format. The second cause was PHP 8x now flagging use of a non integral floating point number in an array index as a potential rounding issue. I doubt that the rounding issue would have caused any issues in the exif handling, though.

It was simply a mistake to make that conversion. The error impacted any floating point value in the image. But in the case of your image it only impacted "digital zoom" and an "unknown" bit of data. It was the latter that caused the fault.

There is a new DEV build that has all these changes.
