### ISSUE TITLE
Can't login anymore after update marathon from 1.3.x to 2.x

### ISSUE THREAD

**Issue by Heart1010** [netPhotoGraphics/netPhotoGraphics#1479]
I upgraded an old zenphoto installation step by step up to 2.x archive - didn't have any problems on all those updates.
But now with 1.9x (or 2.x) after extract.php is finish I have to login again (like with every other update before) but now my admin user and password don't work anymore 😢 
```Es ist ein Fehler beim Anmelden aufgetreten.
Überprüfen Sie Ihren Benutzer und Ihr Passwort und versuchen Sie es erneut.
```
How can I solve that?
Directly in the mysql db? zp_administrators? What should I do so I can login again to make that final update to v2.x?

Thanks

**Comment by sbillard** [comment]
I am sorry your user/password do not work any longer. I have not seen this happen before. Generally speaking if you were logged in before the update you should not have needed to log in after the extract.php has finished.

The solution depends a bit on if you have other users and/or user groups established. If you have no other  users (and therefore no use of groups) then you use your mySQL administrator to drop your administrators table. Run setup then and it will not ask for a password. When setup completes you will be prompted to create your administrator user.

If you have other users the one with the "most" rights is promoted to the site administrator. Log in as that user and after completing setup go to your own user on the user page and set your password again. If you cannot log in as the new master user you will have to use the process above. But if so your other users will have to re-establish their accounts.

Once your lie again, check your logs to see if any errors have been reported.

**Comment by sbillard** [comment]
Glad you have things up and running again. 

The root index.php file is updated by setup, so I am guessing that since you could not log into setup the update did not get done. If the index.php file was from the zenphoto install it is possible it had wrong file permissions and therefore setup could not replace it. But then you should have got some kind of error message I would think. Maybe that is the message that was in the server log?

You should probably run setup now that you can log in to be sure nothing else got skipped.
