### ISSUE TITLE
Can't translate the some English phrases

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1504]
I keep translating and I can't translate the following English phrases. Could you please take a look at them?

![001](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/9a67f459-b544-4037-a838-581e1ab4d7a6)

![002](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/1c09cc5c-1e02-40db-b8f3-348d101e8c24)

![003](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/3feed1cb-cac4-4697-8a82-73280d1e1ad7)

![005](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/ec16c8ea-f85e-4947-af50-a47c4b6b1695)

![006](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/0ff257c7-25a7-44a7-8f33-a18318e243bb)

![007](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/1daf3d1c-41c7-484e-8aad-7e780177e4ac)

**Comment by sbillard** [comment]
I have fixed the first not-translated. The second is caused (I believe) because you had not updated the PO files from the source before translating. I do not update the PO files as a matter of course since few people are doing translations. Please always do Update from source when you have a new nPG release just to be sure you have the latest translation strings.

Changes are in: https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.18.02.06.zip

**Comment by Mates-K1** [comment]
I think it was a combination of everything - a bad search (I'm looking for webp, but it has code with a variable), a typo, and probably an update (I'm trying to download the DEV version).

Anyway, thanks for the correction and I have two minor typos in the code:

- npgCore/admin_options/general.php - line183 - "Invaid"
- npgCore/lib-auth.php - line 158 - "gettest"
