### ISSUE TITLE
Upgrade threw Mariadb error

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1587]
Received this warning when I upgraded to 2.01.00.13 today

![Screen Shot 2024-07-30 at 2 56 24 PM](https://github.com/user-attachments/assets/7e94947e-cd44-4ecc-90f1-07f20a39b59c)

Installation continued without further problem.  Viewing of photo gallery doesn't show any problems.  Haven't tried anything that might involve writing data to the database.

NK

**Comment by sbillard** [comment]
There should be an entry in the debug log or setup log for this query. WIthout some more details it will be pretty hard to know which query is wrong. Presumably this was caused by a change in the database structure. There are two things that have changed on this release. 

First, the _userAddressFields_ plugin has added 'company' and 'phone' fields if you have it enabled.

Second, the tags 'name' field collation will be changed to _utf8mb4_0900_as_ci_ if the database supports it. This is to allow accent sensitive tags. Previously mySQL ignored tags in comparisons.

If either of these failed, thing will still work as before. But the error will presumably recur when setup is run.

I use MySQL, not MariaDB, so there could be a syntax difference between them as well.

It would really help if you can provide the SQL that failed, presumably from the logs. Otherwise let me know if either of these database changes happened and if your MariaDB supports _utf8mb4_0900_as_ci_ .

**Comment by sbillard** [comment]
Found the problem. There is a double parenthesis in setting some keys.
e.g. `ALTER TABLE `_albums` ADD UNIQUE `album` ((`folder`)) COMMENT 'npg';`
 Syntactically that should be redundant, but I guess MariaDB doesn't like them.

Fix will be available shortly. The failure may have created a bad index, but should not be damaging.

**Comment by nerdykit** [comment]
Thanks.
